### ISSUE TITLE
Camera sensitivity and movement speed are inconsistent when the simulation is on the runner thread

### ISSUE THREAD

**Issue by QuartzFox** [slojanko/GMReactPhysics3D#2]
As the fps drops on the runner thread, so does the camera sensitivity and movement speed. Implementing a form of DeltaTime control could alleviate the issue. Attached is a video showing the problem. 

https://user-images.githubusercontent.com/65092445/231595135-0a5348e9-4b25-4c9f-882b-44d3b1b00af3.mp4

Outside of this issue, I'd like to say amazing work on this project. It's amazing to see that this is even possible in GameMaker.

**Comment by slojanko** [comment]
Hey, 

thanks for suggesting this improvement. The commit [07fa67e](https://github.com/slojanko/GMReactPhysics3D/commit/07fa67e3940e27104a2703c963445d651309b675) has frame independent camera controls. 

I'll close this issue tomorrow if everything else is fine regarding the change.
